elastic:
  image:
    docker.uncharted.software/distil_dev_es:latest
  ports:
    - "9200:9200"
postgres:
  image:
    docker.uncharted.software/distil_dev_postgres:latest
  ports:
    - "5432:5432"
  command:
    -d postgres
resources:
  image:
    docker.uncharted.software/distil_res_server:latest
  ports:
    - "5440:5440"
# SRI config here
sri-tpot:
  image:
    registry.datadrivendiscovery.org/j18_ta2eval/sri_tpot:stable
  ports:
    - "45042:45042"
  volumes:
    - /tmp/d3m:/tmp/d3m
  command:
    - ta2_server
    - /tmp/d3m/config/config.json
